

export const rooms = [
    {
      "id": 1,
      "title": "Engine Room",
      "description": "Home of engine",
      "x": 0,
      "y": 0,
      "s_to": -1,
      "w_to": -1,
      "e_to": 21,
      "n_to": 99
    },
    {
      "id": 2,
      "title": "Defense Center",
      "description": "Place of defense",
      "x": 1,
      "y": 8,
      "s_to": 97,
      "w_to": 55,
      "e_to": 18,
      "n_to": 76
    },
    {
      "id": 3,
      "title": "Command Center",
      "description": "Place of planning",
      "x": 3,
      "y": 6,
      "s_to": 6,
      "w_to": 74,
      "e_to": 26,
      "n_to": 47
    },
    {
      "id": 4,
      "title": "Captain Quaters",
      "description": "Captain's Hangout",
      "x": 7,
      "y": 2,
      "s_to": 46,
      "w_to": 87,
      "e_to": 72,
      "n_to": 11
    },
    {
      "id": 5,
      "title": "Bridge",
      "description": "Navigation Center",
      "x": 9,
      "y": 9,
      "s_to": 42,
      "w_to": 92,
      "e_to": -1,
      "n_to": -1
    },
    {
      "id": 6,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 3,
      "y": 5,
      "s_to": 94,
      "w_to": 81,
      "e_to": 10,
      "n_to": 3
    },
    {
      "id": 7,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 3,
      "y": 2,
      "s_to": 91,
      "w_to": 75,
      "e_to": 57,
      "n_to": 64
    },
    {
      "id": 8,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 1,
      "y": 2,
      "s_to": 13,
      "w_to": 52,
      "e_to": 75,
      "n_to": 51
    },
    {
      "id": 9,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 7,
      "y": 0,
      "s_to": -1,
      "w_to": 100,
      "e_to": 67,
      "n_to": 46
    },
    {
      "id": 10,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 4,
      "y": 5,
      "s_to": 44,
      "w_to": 6,
      "e_to": 77,
      "n_to": 26
    },
    {
      "id": 11,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 7,
      "y": 3,
      "s_to": 4,
      "w_to": 35,
      "e_to": 36,
      "n_to": 69
    },
    {
      "id": 12,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 6,
      "y": 7,
      "s_to": 39,
      "w_to": 43,
      "e_to": 20,
      "n_to": 58
    },
    {
      "id": 13,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 1,
      "y": 1,
      "s_to": 21,
      "w_to": 99,
      "e_to": 70,
      "n_to": 8
    },
    {
      "id": 14,
      "title": "Mess Hall",
      "description": "A large room with tables for eating, food is everwhere",
      "x": 2,
      "y": 0,
      "s_to": -1,
      "w_to": 21,
      "e_to": 54,
      "n_to": 70
    },
    {
      "id": 15,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 2,
      "y": 7,
      "s_to": 74,
      "w_to": 97,
      "e_to": 47,
      "n_to": 18
    },
    {
      "id": 16,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 7,
      "y": 8,
      "s_to": 20,
      "w_to": 58,
      "e_to": 98,
      "n_to": 62
    },
    {
      "id": 17,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 1,
      "y": 6,
      "s_to": 27,
      "w_to": 53,
      "e_to": 74,
      "n_to": 97
    },
    {
      "id": 18,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 2,
      "y": 8,
      "s_to": 15,
      "w_to": 2,
      "e_to": 25,
      "n_to": 28
    },
    {
      "id": 19,
      "title": "Mess Hall",
      "description": "A large room with tables for eating, food is everwhere",
      "x": 9,
      "y": 6,
      "s_to": 50,
      "w_to": 40,
      "e_to": -1,
      "n_to": 86
    },
    {
      "id": 20,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 7,
      "y": 7,
      "s_to": 34,
      "w_to": 12,
      "e_to": 84,
      "n_to": 16
    },
    {
      "id": 21,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 1,
      "y": 0,
      "s_to": -1,
      "w_to": 1,
      "e_to": 14,
      "n_to": 13
    },
    {
      "id": 22,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 5,
      "y": 9,
      "s_to": 23,
      "w_to": 93,
      "e_to": 49,
      "n_to": -1
    },
    {
      "id": 23,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 5,
      "y": 8,
      "s_to": 43,
      "w_to": 78,
      "e_to": 58,
      "n_to": 22
    },
    {
      "id": 24,
      "title": "Weapons",
      "description": "",
      "x": 6,
      "y": 1,
      "s_to": 100,
      "w_to": 73,
      "e_to": 46,
      "n_to": 87
    },
    {
      "id": 25,
      "title": "Engineering Bay",
      "description": "Place of engineering",
      "x": 3,
      "y": 8,
      "s_to": 47,
      "w_to": 18,
      "e_to": 78,
      "n_to": 48
    },
    {
      "id": 26,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 4,
      "y": 6,
      "s_to": 10,
      "w_to": 3,
      "e_to": 65,
      "n_to": 83
    },
    {
      "id": 27,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 1,
      "y": 5,
      "s_to": 63,
      "w_to": 45,
      "e_to": 81,
      "n_to": 17
    },
    {
      "id": 28,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 2,
      "y": 9,
      "s_to": 18,
      "w_to": 76,
      "e_to": 48,
      "n_to": -1
    },
    {
      "id": 29,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 4,
      "y": 0,
      "s_to": -1,
      "w_to": 54,
      "e_to": 82,
      "n_to": 85
    },
    {
      "id": 30,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 5,
      "y": 2,
      "s_to": 73,
      "w_to": 57,
      "e_to": 87,
      "n_to": 89
    },
    {
      "id": 31,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 0,
      "y": 4,
      "s_to": 41,
      "w_to": -1,
      "e_to": 63,
      "n_to": 45
    },
    {
      "id": 32,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 9,
      "y": 1,
      "s_to": 95,
      "w_to": 59,
      "e_to": -1,
      "n_to": 60
    },
    {
      "id": 33,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 2,
      "y": 3,
      "s_to": 75,
      "w_to": 51,
      "e_to": 64,
      "n_to": 79
    },
    {
      "id": 34,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 7,
      "y": 6,
      "s_to": 38,
      "w_to": 39,
      "e_to": 40,
      "n_to": 20
    },
    {
      "id": 35,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 6,
      "y": 3,
      "s_to": 87,
      "w_to": 89,
      "e_to": 11,
      "n_to": 90
    },
    {
      "id": 36,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 8,
      "y": 3,
      "s_to": 72,
      "w_to": 11,
      "e_to": 66,
      "n_to": 37
    },
    {
      "id": 37,
      "title": "Engineering Bay",
      "description": "Place of engineering",
      "x": 8,
      "y": 4,
      "s_to": 36,
      "w_to": 69,
      "e_to": 80,
      "n_to": 68
    },
    {
      "id": 38,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 7,
      "y": 5,
      "s_to": 69,
      "w_to": 61,
      "e_to": 68,
      "n_to": 34
    },
    {
      "id": 39,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 6,
      "y": 6,
      "s_to": 61,
      "w_to": 65,
      "e_to": 34,
      "n_to": 12
    },
    {
      "id": 40,
      "title": "Weapons",
      "description": "",
      "x": 8,
      "y": 6,
      "s_to": 68,
      "w_to": 34,
      "e_to": 19,
      "n_to": 84
    },
    {
      "id": 41,
      "title": "Medical Bay",
      "description": "Lot of medical supplies still around",
      "x": 0,
      "y": 3,
      "s_to": 52,
      "w_to": -1,
      "e_to": 51,
      "n_to": 31
    },
    {
      "id": 42,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 9,
      "y": 8,
      "s_to": 86,
      "w_to": 98,
      "e_to": -1,
      "n_to": 5
    },
    {
      "id": 43,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 5,
      "y": 7,
      "s_to": 65,
      "w_to": 83,
      "e_to": 12,
      "n_to": 23
    },
    {
      "id": 44,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 4,
      "y": 4,
      "s_to": 56,
      "w_to": 94,
      "e_to": 96,
      "n_to": 10
    },
    {
      "id": 45,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 0,
      "y": 5,
      "s_to": 31,
      "w_to": -1,
      "e_to": 27,
      "n_to": 53
    },
    {
      "id": 46,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 7,
      "y": 1,
      "s_to": 9,
      "w_to": 24,
      "e_to": 59,
      "n_to": 4
    },
    {
      "id": 47,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 3,
      "y": 7,
      "s_to": 3,
      "w_to": 15,
      "e_to": 83,
      "n_to": 25
    },
    {
      "id": 48,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 3,
      "y": 9,
      "s_to": 25,
      "w_to": 28,
      "e_to": 93,
      "n_to": -1
    },
    {
      "id": 49,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 6,
      "y": 9,
      "s_to": 58,
      "w_to": 22,
      "e_to": 62,
      "n_to": -1
    },
    {
      "id": 50,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 9,
      "y": 5,
      "s_to": 80,
      "w_to": 68,
      "e_to": -1,
      "n_to": 19
    },
    {
      "id": 51,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 1,
      "y": 3,
      "s_to": 8,
      "w_to": 41,
      "e_to": 33,
      "n_to": 63
    },
    {
      "id": 52,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 0,
      "y": 2,
      "s_to": 99,
      "w_to": -1,
      "e_to": 8,
      "n_to": 41
    },
    {
      "id": 53,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 0,
      "y": 6,
      "s_to": 45,
      "w_to": -1,
      "e_to": 17,
      "n_to": 71
    },
    {
      "id": 54,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 3,
      "y": 0,
      "s_to": -1,
      "w_to": 14,
      "e_to": 29,
      "n_to": 91
    },
    {
      "id": 55,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 0,
      "y": 8,
      "s_to": 71,
      "w_to": -1,
      "e_to": 2,
      "n_to": 88
    },
    {
      "id": 56,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 4,
      "y": 3,
      "s_to": 57,
      "w_to": 64,
      "e_to": 89,
      "n_to": 44
    },
    {
      "id": 57,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 4,
      "y": 2,
      "s_to": 85,
      "w_to": 7,
      "e_to": 30,
      "n_to": 56
    },
    {
      "id": 58,
      "title": "Mess Hall",
      "description": "A large room with tables for eating, food is everwhere",
      "x": 6,
      "y": 8,
      "s_to": 12,
      "w_to": 23,
      "e_to": 16,
      "n_to": 49
    },
    {
      "id": 59,
      "title": "Mess Hall",
      "description": "A large room with tables for eating, food is everwhere",
      "x": 8,
      "y": 1,
      "s_to": 67,
      "w_to": 46,
      "e_to": 32,
      "n_to": 72
    },
    {
      "id": 60,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 9,
      "y": 2,
      "s_to": 32,
      "w_to": 72,
      "e_to": -1,
      "n_to": 66
    },
    {
      "id": 61,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 6,
      "y": 5,
      "s_to": 90,
      "w_to": 77,
      "e_to": 38,
      "n_to": 39
    },
    {
      "id": 62,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 7,
      "y": 9,
      "s_to": 16,
      "w_to": 49,
      "e_to": 92,
      "n_to": -1
    },
    {
      "id": 63,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 1,
      "y": 4,
      "s_to": 51,
      "w_to": 31,
      "e_to": 79,
      "n_to": 27
    },
    {
      "id": 64,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 3,
      "y": 3,
      "s_to": 7,
      "w_to": 33,
      "e_to": 56,
      "n_to": 94
    },
    {
      "id": 65,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 5,
      "y": 6,
      "s_to": 77,
      "w_to": 26,
      "e_to": 39,
      "n_to": 43
    },
    {
      "id": 66,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 9,
      "y": 3,
      "s_to": 60,
      "w_to": 36,
      "e_to": -1,
      "n_to": 80
    },
    {
      "id": 67,
      "title": "Mess Hall",
      "description": "A large room with tables for eating, food is everwhere",
      "x": 8,
      "y": 0,
      "s_to": -1,
      "w_to": 9,
      "e_to": 95,
      "n_to": 59
    },
    {
      "id": 68,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 8,
      "y": 5,
      "s_to": 37,
      "w_to": 38,
      "e_to": 50,
      "n_to": 40
    },
    {
      "id": 69,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 7,
      "y": 4,
      "s_to": 11,
      "w_to": 90,
      "e_to": 37,
      "n_to": 38
    },
    {
      "id": 70,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 2,
      "y": 1,
      "s_to": 14,
      "w_to": 13,
      "e_to": 91,
      "n_to": 75
    },
    {
      "id": 71,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 0,
      "y": 7,
      "s_to": 53,
      "w_to": -1,
      "e_to": 97,
      "n_to": 55
    },
    {
      "id": 72,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 8,
      "y": 2,
      "s_to": 59,
      "w_to": 4,
      "e_to": 60,
      "n_to": 36
    },
    {
      "id": 73,
      "title": "Medical Bay",
      "description": "Lot of medical supplies still around",
      "x": 5,
      "y": 1,
      "s_to": 82,
      "w_to": 85,
      "e_to": 24,
      "n_to": 30
    },
    {
      "id": 74,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 2,
      "y": 6,
      "s_to": 81,
      "w_to": 17,
      "e_to": 3,
      "n_to": 15
    },
    {
      "id": 75,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 2,
      "y": 2,
      "s_to": 70,
      "w_to": 8,
      "e_to": 7,
      "n_to": 33
    },
    {
      "id": 76,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 1,
      "y": 9,
      "s_to": 2,
      "w_to": 88,
      "e_to": 28,
      "n_to": -1
    },
    {
      "id": 77,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 5,
      "y": 5,
      "s_to": 96,
      "w_to": 10,
      "e_to": 61,
      "n_to": 65
    },
    {
      "id": 78,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 4,
      "y": 8,
      "s_to": 83,
      "w_to": 25,
      "e_to": 23,
      "n_to": 93
    },
    {
      "id": 79,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 2,
      "y": 4,
      "s_to": 33,
      "w_to": 63,
      "e_to": 94,
      "n_to": 81
    },
    {
      "id": 80,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 9,
      "y": 4,
      "s_to": 66,
      "w_to": 37,
      "e_to": -1,
      "n_to": 50
    },
    {
      "id": 81,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 2,
      "y": 5,
      "s_to": 79,
      "w_to": 27,
      "e_to": 6,
      "n_to": 74
    },
    {
      "id": 82,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 5,
      "y": 0,
      "s_to": -1,
      "w_to": 29,
      "e_to": 100,
      "n_to": 73
    },
    {
      "id": 83,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 4,
      "y": 7,
      "s_to": 26,
      "w_to": 47,
      "e_to": 43,
      "n_to": 78
    },
    {
      "id": 84,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 8,
      "y": 7,
      "s_to": 40,
      "w_to": 20,
      "e_to": 86,
      "n_to": 98
    },
    {
      "id": 85,
      "title": "Weapons",
      "description": "",
      "x": 4,
      "y": 1,
      "s_to": 29,
      "w_to": 91,
      "e_to": 73,
      "n_to": 57
    },
    {
      "id": 86,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 9,
      "y": 7,
      "s_to": 19,
      "w_to": 84,
      "e_to": -1,
      "n_to": 42
    },
    {
      "id": 87,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 6,
      "y": 2,
      "s_to": 24,
      "w_to": 30,
      "e_to": 4,
      "n_to": 35
    },
    {
      "id": 88,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 0,
      "y": 9,
      "s_to": 55,
      "w_to": -1,
      "e_to": 76,
      "n_to": -1
    },
    {
      "id": 89,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 5,
      "y": 3,
      "s_to": 30,
      "w_to": 56,
      "e_to": 35,
      "n_to": 96
    },
    {
      "id": 90,
      "title": "Recreation Center",
      "description": "A room with excercise equipment and foosball tables",
      "x": 6,
      "y": 4,
      "s_to": 35,
      "w_to": 96,
      "e_to": 69,
      "n_to": 61
    },
    {
      "id": 91,
      "title": "Mess Hall",
      "description": "A large room with tables for eating, food is everwhere",
      "x": 3,
      "y": 1,
      "s_to": 54,
      "w_to": 70,
      "e_to": 85,
      "n_to": 7
    },
    {
      "id": 92,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 8,
      "y": 9,
      "s_to": 98,
      "w_to": 62,
      "e_to": 5,
      "n_to": -1
    },
    {
      "id": 93,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 4,
      "y": 9,
      "s_to": 78,
      "w_to": 48,
      "e_to": 22,
      "n_to": -1
    },
    {
      "id": 94,
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 3,
      "y": 4,
      "s_to": 64,
      "w_to": 79,
      "e_to": 44,
      "n_to": 6
    },
    {
      "id": 95,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 9,
      "y": 0,
      "s_to": -1,
      "w_to": 67,
      "e_to": -1,
      "n_to": 32
    },
    {
      "id": 96,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 5,
      "y": 4,
      "s_to": 89,
      "w_to": 44,
      "e_to": 90,
      "n_to": 77
    },
    {
      "id": 97,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 1,
      "y": 7,
      "s_to": 17,
      "w_to": 71,
      "e_to": 15,
      "n_to": 2
    },
    {
      "id": 98,
      "title": "Bathroom",
      "description": "The cleanest bathroom you've ever seen",
      "x": 8,
      "y": 8,
      "s_to": 84,
      "w_to": 16,
      "e_to": 42,
      "n_to": 92
    },
    {
      "id": 99,
      "title": "Hallway",
      "description": "A corridor with red emergency lights illuminating the room and the occasional sparks from loose wires",
      "x": 0,
      "y": 1,
      "s_to": 1,
      "w_to": -1,
      "e_to": 13,
      "n_to": 52
    },
    {  
      "title": "Crew Cabin",
      "description": "A crew members cabin with a small mattress and mementos",
      "x": 6,
      "y": 0,
      "s_to": -1,
      "w_to": 82,
      "e_to": 9,
      "n_to": 24
    }
  ]